apiVersion: v1
kind: Service
metadata:
  name: go-homelab-service
  namespace: observability
  labels:
    app: go-homelab # O ServiceMonitor busca por isso
spec:
  type: NodePort
  selector:
    app: go-homelab
  ports:
    - name: metrics # O NOME É OBRIGATÓRIO PARA O SERVICEMONITOR
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
